### ISSUE TITLE
Latest version 1.7.3 not working

### ISSUE THREAD

**Issue by ocha** [arkokoley/pdfvuer#79]
Im getting following errors: `"export 'default' (imported as 'pdfvuer') was not found in 'pdfvuer'`

I have following statement inside my vue file: `import pdfvuer from 'pdfvuer'`. If I use v1.6.1 then everything works fine. 

Any thoughts?

**Comment by tipsclick** [comment]
facing same issue
Uncaught (in promise) TypeError: Cannot read property '_c' of undefined

**Comment by arkokoley** [comment]
Fixed in https://www.npmjs.com/package/pdfvuer/v/1.7.5

**Comment by ocha** [comment]
@arkokoley This is still not working. I am getting exactly same error as with 1.7.3: `"export 'default' (imported as 'pdfvuer') was not found in 'pdfvuer'`
```
"export 'default' (imported as 'pdfvuer') was not found in 'pdfvuer'
    at HarmonyImportSpecifierDependency._getErrors (/REDACTED/node_modules/webpack/lib/dependencies/HarmonyImportSpecifierDependency.js:109:11)
    at HarmonyImportSpecifierDependency.getErrors (/REDACTED/node_modules/webpack/lib/dependencies/HarmonyImportSpecifierDependency.js:68:16)
    at Compilation.reportDependencyErrorsAndWarnings (/REDACTED/node_modules/webpack/lib/Compilation.js:1463:22)
```

**Comment by arkokoley** [comment]
Hi,

Can you try importing as:

import {default as pdfvuer} from 'pdfvuer';

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by ocha** [comment]
getting error: `"export 'default' (imported as 'pdfvuer') was not found in 'pdfvuer'`

**Comment by arkokoley** [comment]
How are you compiling your app? Vue-cli-service or webpack? Or something else?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by ocha** [comment]
compiling it with webpack 4

**Comment by arkokoley** [comment]
Can you share your webpack config? I'd take a look at this tomorrow. This seems to related to https://github.com/webpack/webpack/issues/4817

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by ocha** [comment]
Thanks for looking into this. I created smallest example from my config that will break. here is the repo link: https://github.com/ocha/pdfvuer_test/

If you change version of pdfvuer to `=1.6.1` in package.json, and run `yarn install`, then it will work. 1.7.3 and 1.7.5 are broken.

**Comment by arkokoley** [comment]
@ocha this seems to work with vue-cli-service but not the webpack config that you have shared. It will be interesting to see what is missing from the webpack config.
